version: "3.7"
services: 
  database:
    image: postgres
    restart: always
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - databases
  pgadmin:
    image: dpage/pgadmin4
    env_file: 
      - .env
    ports:
      - "5050:80"
    networks:
      - databases
    
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - databases
    ports:
      - "8080:8080"
volumes:
  data:
networks:
  databases:
